### ISSUE TITLE
L10N issues in 1.2.2

### ISSUE THREAD

**Issue by alexclassroom** [terrylinooo/wp-shieldon#1]
我將我在 1.2.2 版中找到的某些本地化問題，直接以修改過的程式碼列於下方。

1. \src\views\dashboard\dashboard_today.php, Line 196
`text: ['<?php _e( 'Past 7 hours', 'wp-shieldon' ); ?>'],`
2. \src\views\setting\about.php, Line 19
`<?php printf( __( 'WP Shieldon is brought to you by <a href="%1$s">Terry L.</a> from <a href="%2$s">Taiwan</a>.', 'wp-shieldon' ), 'https://terryl.in', 'https://www.google.com/maps/@23.4722181,120.9910232,8z'); ?>`
3. \src\class-wpso-admin-settings.php, Line 147
`'desc'    => __( 'Is your website behind CDN service? If you use CDN, you have to set this setting, otherwise all IP addresses come from CDN servers, they will be banned.', 'wp-shieldon' ),`
4. \src\class-wpso-admin-settings.php, Line 152 - 157
```
'no'         => __( 'No', 'wp-shieldon' ),
'cloudflare' => __( 'CloudFlare (HTTP_CF_CONNECTING_IP)', 'wp-shieldon' ),
'google'     => __( 'Google Cloud CDN or Load Balancer (HTTP_X_FORWARDED_FOR)', 'wp-shieldon' ),
'aws'        => __( 'AWS CouldFront (HTTP_X_FORWARDED_FOR)', 'wp-shieldon' ),
'keycdn'     => __( 'KeyCDN (HTTP_X_FORWARDED_HOST)', 'wp-shieldon' ),
'others'     => __( 'Others (HTTP_X_FORWARDED_FOR)', 'wp-shieldon' ),
```
5. \src\class-wpso-admin-settings.php, Line 580 - 582
```
'alnum'   => __( 'Alpha-numeric string with lower and uppercase characters.', 'wp-shieldon' ),
'alpha'   => __( 'A string with lower and uppercase letters only.', 'wp-shieldon' ),
'numeric' => __( 'Numeric string only.', 'wp-shieldon' ),
```

**Comment by terrylinooo** [comment]
好的。謝謝。

**Comment by terrylinooo** [comment]
謝謝，已更新。下星期來好好整理一下文章。
