### ISSUE TITLE
wordpress.org 1.5.0版

### ISSUE THREAD

**Issue by lafinlalannges** [terrylinooo/wp-shieldon#2]
在 Wordpress.org 的 1.5.0版本中，對 Multisite 的 issue 有過嗎？
我目前 multisite 含主網域共三個網站，主網站跟第二站都正常，唯獨新增一個新的 multisite後，可以讀取首頁，但若要進後台會出現在附檔中的訊息。
目前只能先將外掛停用才能讓第三個站正常進入後台

[lavot.work.wp-errors.log](https://github.com/terrylinooo/wp-shieldon/files/4040400/lavot.work.wp-errors.log)

**Comment by terrylinooo** [comment]
這個週末會增加新功能，版本為 1.6.0。這個問題會解決。
謝謝您的回報。

**Comment by lafinlalannges** [comment]
update 一下，我目前發現，發生問題後，暫停 WP-Shieldon 的服務，再進後台做後續的基礎設定，再啟用 WP-Shieldon，竟然就正常了。

但是再新增新的 Multisite 的話，仍又是最早我講的問題一樣，除非像我前面一段講的，每次新增新的 multisite前先暫停 WP-Shieldon，做好設定後再開啟服務，但這樣實在太累～

以上，期盼新版更新後這樣的問題有機會獲得解決，謝謝你寫出這麼優質的軟體

**Comment by terrylinooo** [comment]
謝謝回報。目前新版功能較多，我還在一一測試，這個問題有掌握在新版解決，請再稍等幾天

**Comment by terrylinooo** [comment]
請更新至 1.6.0 版。
